name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      
      - name: Run ps1 script
        run: |
          dir
          cd ../
          dir
          cd ../
          dir
          powershell Set-ExecutionPolicy Unrestricted
          powershell ../../setup.ps1
