name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Run ps1 script
        run: |
        powershell Set-ExecutionPolicy Unrestricted
        powershell ./setup.ps1